### PR TITLE
feat: bump blocksuite

### PR DESCRIPTION
**Pull request by doodlewind**
https://github.com/toeverything/blocksuite/compare/b6302df...e8d6e1d

Note that the `nightly` channel has been replaced by `canary` in https://github.com/toeverything/blocksuite/pull/6172

## Features
- https://github.com/toeverything/BlockSuite/pull/6173 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6166 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6158 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/6147 @AyushAgrawal-A2

## Bugfix
- https://github.com/toeverything/BlockSuite/pull/6164 @regischen
- https://github.com/toeverything/BlockSuite/pull/6163 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6161 @doouding
- https://github.com/toeverything/BlockSuite/pull/6160 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6159 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6157 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6154 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6152 @lawvs
- https://github.com/toeverything/BlockSuite/pull/6150 @regischen
- https://github.com/toeverything/BlockSuite/pull/6151 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6148 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6146 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6144 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6142 @lawvs
- https://github.com/toeverything/BlockSuite/pull/6141 @AyushAgrawal-A2

## Refactor
- https://github.com/toeverything/BlockSuite/pull/6165 @regischen

## Misc
- https://github.com/toeverything/BlockSuite/pull/6172 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/6171 @JimmFly
- chore: update site style
- https://github.com/toeverything/BlockSuite/pull/6170 @doodlewind
- docs: update overview
- https://github.com/toeverything/BlockSuite/pull/6156 @doouding
- https://github.com/toeverything/BlockSuite/pull/6155 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/6138 @donteatfriedrice

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
You should also change renovate config: https://github.com/toeverything/AFFiNE/blob/canary/.github/renovate.json#L54
And there is an existed pull request here: https://github.com/toeverything/AFFiNE/pull/5764

**Comment by doodlewind** [comment]
> You should also change renovate config: https://github.com/toeverything/AFFiNE/blob/canary/.github/renovate.json#L54

Fixed.

> And there is an existed pull request here: https://github.com/toeverything/AFFiNE/pull/5764

This PR is newer, but the generated PR description seems to not work here :(

**Comment by Brooooooklyn** [comment]
> This PR is newer, but the generated PR description seems to not work here :(

Auto-generate changelog will work after https://app.graphite.dev/github/pr/toeverything/AFFiNE/5763/chore-change-bump-blocksuite-script-to-js merge

**Comment by Brooooooklyn** [comment]
@doodlewind I'll help you to rebase the latest changes

**Review by pengx17 — APPROVED** [review]

**Comment by joooye34** [comment]
test:
## Features
- https://github.com/toeverything/BlockSuite/pull/6131 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6122 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/6105 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/6107 @fourdim
- https://github.com/toeverything/BlockSuite/pull/5970 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/6069 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6090 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6067 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6065 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/6029 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6033 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6030 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6032 @Flrande
- https://github.com/toeverything/BlockSuite/pull/5969 @darkskygit
- https://github.com/toeverything/BlockSuite/pull/6017 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6015 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5994 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6010 @regischen
- https://github.com/toeverything/BlockSuite/pull/6011 @lawvs
- https://github.com/toeverything/BlockSuite/pull/5998 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5997 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5988 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5993 @Flrande
- https://github.com/toeverything/BlockSuite/pull/5995 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5955 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5963 @darkskygit
- https://github.com/toeverything/BlockSuite/pull/5927 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5952 @regischen
- https://github.com/toeverything/BlockSuite/pull/5949 @fourdim
- https://github.com/toeverything/BlockSuite/pull/5947 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/5943 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/5918 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/5917 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5862 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/5909 @Flrande
- https://github.com/toeverything/BlockSuite/pull/5905 @fourdim
- https://github.com/toeverything/BlockSuite/pull/5911 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5904 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5900 @doouding
- https://github.com/toeverything/BlockSuite/pull/5888 @doouding
- https://github.com/toeverything/BlockSuite/pull/5889 @Saul-Mirone

## Bugfix
- https://github.com/toeverything/BlockSuite/pull/6141 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6140 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6139 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6135 @regischen
- https://github.com/toeverything/BlockSuite/pull/6132 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6130 @doouding
- https://github.com/toeverything/BlockSuite/pull/6124 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6128 @regischen
- https://github.com/toeverything/BlockSuite/pull/6126 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6127 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6119 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6117 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6118 @regischen
- https://github.com/toeverything/BlockSuite/pull/6116 @regischen
- https://github.com/toeverything/BlockSuite/pull/6114 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6113 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6111 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6110 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6099 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6109 @fourdim
- https://github.com/toeverything/BlockSuite/pull/6102 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6098 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6097 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6100 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6104 @lawvs
- https://github.com/toeverything/BlockSuite/pull/6095 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6093 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6089 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6085 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6087 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6088 @doouding
- https://github.com/toeverything/BlockSuite/pull/6091 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6084 @doouding
- https://github.com/toeverything/BlockSuite/pull/6081 @regischen
- https://github.com/toeverything/BlockSuite/pull/6074 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/6076 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6075 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6064 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6060 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6059 @zqran
- https://github.com/toeverything/BlockSuite/pull/6050 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6037 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6031 @regischen
- https://github.com/toeverything/BlockSuite/pull/6024 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6026 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6025 @regischen
- https://github.com/toeverything/BlockSuite/pull/6023 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6022 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/6021 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6009 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6008 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6005 @nawbc
- https://github.com/toeverything/BlockSuite/pull/6003 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/6000 @fourdim
- https://github.com/toeverything/BlockSuite/pull/5990 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5986 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5987 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5985 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5980 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5984 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5981 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5979 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5982 @Flrande
- https://github.com/toeverything/BlockSuite/pull/5975 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5974 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5971 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5968 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5967 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5973 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5965 @regischen
- https://github.com/toeverything/BlockSuite/pull/5964 @fourdim
- https://github.com/toeverything/BlockSuite/pull/5962 @regischen
- https://github.com/toeverything/BlockSuite/pull/5959 @regischen
- https://github.com/toeverything/BlockSuite/pull/5958 @water-in-stone
- https://github.com/toeverything/BlockSuite/pull/5951 @regischen
- https://github.com/toeverything/BlockSuite/pull/5946 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5945 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5944 @fourdim
- https://github.com/toeverything/BlockSuite/pull/5936 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5932 @lawvs
- https://github.com/toeverything/BlockSuite/pull/5930 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5929 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5926 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5921 @doouding
- https://github.com/toeverything/BlockSuite/pull/5923 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/5915 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5914 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/5913 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5907 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5903 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5902 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/5898 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5895 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5892 @umar23faiz
- https://github.com/toeverything/BlockSuite/pull/5891 @lawvs

## Refactor
- https://github.com/toeverything/BlockSuite/pull/6133 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/6108 @doouding
- https://github.com/toeverything/BlockSuite/pull/6080 @Saul-Mirone
- https://github.com/toeverything/BlockSuite/pull/6068 @doouding
- https://github.com/toeverything/BlockSuite/pull/5972 @doouding
- https://github.com/toeverything/BlockSuite/pull/5850 @Flrande
- https://github.com/toeverything/BlockSuite/pull/6007 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5954 @zzj3720
- https://github.com/toeverything/BlockSuite/pull/5934 @donteatfriedrice
- https://github.com/toeverything/BlockSuite/pull/5933 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/5874 @doouding
- https://github.com/toeverything/BlockSuite/pull/5908 @doodlewind
- https://github.com/toeverything/BlockSuite/pull/5878 @AyushAgrawal-A2
- https://github.com/toeverything/BlockSuite/pull/5906 @Saul-Mirone

**Pull request merged**
