### PR TITLE
fix: first workspace create logic

### PR DESCRIPTION
**Pull request by pengx17**
- [x] add `@affine/jotai` package. Right now it only has `atomWithSyncStorage` to replace official `atomWithStorage`
- [x] replace all `atomWithStorage` with `atomWithSyncStorage`
- [x] make sure only one workspace will be created if there is only one workspace
- [x] use jotai v2 api 'store.sub' to handle `createFirst` workspace logic

### CODE REVIEW

**Comment by himself65** [comment]
Will this cause the hydration issue?

**Comment by pengx17** [comment]
> Will this cause the hydration issue?

No, I didn't see any so far

**Comment by himself65** [comment]
> > Will this cause the hydration issue?
> 
> No, I didn't see any so far

It's because 

https://github.com/toeverything/AFFiNE/blob/fd65dd66a1943edadc8be633a9139f79c875b83b/apps/web/src/layouts/index.tsx#L159

**Comment by pengx17** [comment]
> It's because
> 
> https://github.com/toeverything/AFFiNE/blob/fd65dd66a1943edadc8be633a9139f79c875b83b/apps/web/src/layouts/index.tsx#L159

Hmm... With this, SSR is always off right? I think our app is not SSR compatible in many other aspects. Do we need to think about supporting SSR with storage now?

**Review by himself65 — APPROVED** [review]

**Pull request merged**
