### PR TITLE
fix: workspace setting avatar flickering

### LINKED ISSUE #1175: Workspace settings avatar flicker
Flicker

Particularly the workspace image will flicker when changing tabs.

You can see a flicker of the default green image in this case.

### PR DESCRIPTION
**Pull request by sinchang**
Fixes #1175 

Kapture 2023-03-04 at 00 05 37

### CODE REVIEW

**Review by himself65 — CHANGES_REQUESTED** [review]
Thanks for contributing, but this is not a good approach.
For example, there're too many if else and undefined and null

I'm thinking of using suspense mode on the whole workspace loading. It need a little time

**Review by himself65 — CHANGES_REQUESTED** [review]
Blocking until https://github.com/toeverything/AFFiNE/pull/1304

**Comment by himself65** [comment]
As I have landed the suspense mode, we can support suspense on avatar now.

**Comment by sinchang** [comment]
> As I have landed the suspense mode, we can support suspense on avatar now.

Could you give me some hints on how to use suspense on the avatar component?

**Comment by himself65** [comment]
> > As I have landed the suspense mode, we can support suspense on avatar now.
> 
> Could you give me some hints on how to use suspense on the avatar component?

Sorry I didn't see the message and I've fix the issue here https://github.com/toeverything/AFFiNE/pull/1319

**Pull request closed without merging**
