### PR TITLE
style(core): add page list header emptypage

### PR DESCRIPTION
**Pull request by rakheesingh**
Issue - #5157
This pull request introduces the integration of the PageListHeader component into the EmptyPage component, enhancing it with a shared header functionality. The addition of this "common header" enhances the overall user interface and provides a cohesive design across different components. This integration promotes code modularity and facilitates a more consistent and streamlined user experience.

### CODE REVIEW

**Comment by EYHN** [comment]
perfect, before I merge this, you need to sign our CLA by click this [link](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=5162).

**Comment by rakheesingh** [comment]
> perfect, before I merge this, you need to sign our CLA by click this [link](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=5162).

done

**Review by EYHN — APPROVED** [review]

**Comment by rakheesingh** [comment]
@EYHN you can merge this PR too.

**Comment by Brooooooklyn** [comment]
@rakhee28 it seems like the email in your commit information is not matched with the GitHub account you are using, so our CLA bot can't find your sign. Could you try to sign our CLA using this account: https://github.com/rakhee28 ?

**Comment by rakhee28** [comment]
> @rakhee28 it seems like the email in your commit information is not matched with the GitHub account you are using, so our CLA bot can't find your sign. Could you try to sign our CLA using this account: https://github.com/rakhee28 ?

done bro

**Review by Brooooooklyn — APPROVED** [review]

**Comment by EYHN** [comment]
Hi, @rakheesingh @rakhee28

Thank you for your contribution.

I'm reaching out to gather your thoughts on the contribution process. How was your experience contributing to Affine? Do you have any suggestions or feedback that could help us improve the process for future contributors?

**Pull request merged**
