### PR TITLE
refactor: remove code repetition

### PR DESCRIPTION
**Pull request by CarlosZoft**
## Description

For each production plugin, there was the same check

## Solution

Check only once

### CODE REVIEW

**Comment by darkskygit** [comment]
webpack plugins need to be in the correct order, no need to adjust the ordering

**Comment by CarlosZoft** [comment]
I understand, but what do you think of something more broken and less polluted?

**Comment by CarlosZoft** [comment]
my suggestion is to create a base configuration and branch into prod environment or not, i can do it.

**Comment by darkskygit** [comment]
we have several other internal projects using the common webpack configuration. we plan to merge into this repository in the near future, and then we will adjust the configuration of the existing projects together.

**Pull request closed without merging**
