### PR TITLE
feat: add animation for history preview

### PR DESCRIPTION
**Pull request by pengx17**
<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/T2klNLEk0wxLh4NRDzhk/5ce45d13-1117-4853-a066-e8ab1446eb4f.mp4">
              
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/T2klNLEk0wxLh4NRDzhk/5ce45d13-1117-4853-a066-e8ab1446eb4f.mp4">Kapture 2024-02-29 at 18.54.15.mp4</video>

### CODE REVIEW

**Comment by pengx17** [comment]
Current dependencies on/for this PR:
* **#5966** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5966?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5966?utm_source=stack-comment).

**Comment by CatsJuice** [comment]
🤔 a little strange, cc @hwangdev97 @zanwei

**Review by EYHN — APPROVED** [review]
[cool](https://app.graphite.dev/settings/meme-library?org=toeverything)

**Comment by pengx17** [comment]
> 🤔 a little strange, cc @hwangdev97 @zanwei 

let me tune it a bit later

**Pull request merged**
