### PR TITLE
feat(web): drag page to favorites folder

### PR DESCRIPTION
**Pull request by SevenOutman**
How could this have been missing ;)

https://user-images.githubusercontent.com/8225666/235942865-1d61bc0f-8b87-48cd-9ae1-a7fe87138d0a.mov

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
This is great but would you like to add some test case

**Review by himself65 — COMMENTED** [review]
@joebeijing

**Comment by SevenOutman** [comment]
> This is great but would you like to add some rest case for the future?

@Himself65 Did you mean test cases?

**Comment by himself65** [comment]
> > This is great but would you like to add some rest case for the future?
> 
> @Himself65 Did you mean test cases?

yeah

**Comment by joebeijing** [comment]
I tried it out and the implementation is good, it completes the first step of dragging and adding to favorites. @Himself65 
And also we plan to add the ability to sort the items in the favorites list by dragging and dropping them in the future.

**Comment by SevenOutman** [comment]
> > > This is great but would you like to add some rest case for the future?
> > 
> > 
> > @Himself65 Did you mean test cases?
> 
> yeah

For sure. I'll add unit tests for the PageListItem component, and I'll see if I can find out how to write e2e tests for drag-and-drop user actions.

**Comment by SevenOutman** [comment]
@Himself65 I noticed that PageList has been largely refactored since my last commit, so I rewrite the changes based on the latest codebase. PageListItem component doesn't exist in the latest edit so I omitted the unit tests.

A E2E case for drag-and-drop is added.

**Comment by SevenOutman** [comment]
I just merged the latest `master` branch. Looks like the `theme` package is moved, so I opened another PR https://github.com/toeverything/design/pull/2 to add the needed theme variable.

Would there be some follow-ups for this PR?

**Comment by SevenOutman** [comment]
Suppressed by #2385

**Pull request closed without merging**
