### PR TITLE
chore(infra): update jotai & jotai-effects

### PR DESCRIPTION
**Pull request by pengx17**
jotai-effect does not work with jotai under version 2.5.0
See https://github.com/jotaijs/jotai-effect/pull/19

also removed infra dep for env, but include env as a dep for infra, which is required in the next stack item.

### CODE REVIEW

**Comment by pengx17** [comment]
Current dependencies on/for this PR:
* canary
  * **PR #5019** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5019?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5019?utm_source=stack-comment).

**Review by joooye34 — APPROVED** [review]

**Comment by joooye34** [comment]
why this PR is after manual update?

**Comment by pengx17** [comment]
> why this PR is after manual update?

Do you mean why these dependencies are not managed by dependbot? I think there are cases that still need human intervention like jotai upgrades.

**Comment by joooye34** [comment]
Do duplicate with https://github.com/toeverything/AFFiNE/pull/5016?

**Comment by pengx17** [comment]
Yes, we can close this one now.

**Pull request closed without merging**
