### PR TITLE
Feature Mail Setting for other than Gmail

### PR DESCRIPTION
**Pull request by saranshisatgit**
This has been already PR'ed but not sure if that was merged so trying again

### CODE REVIEW

**Comment by darkskygit** [comment]
thanks for your pr, please follow the first comment at this pr to sign a cla, then we can review and merge your codes

**Comment by saranshisatgit** [comment]
Trying to sign with CLA assistant but not working out.

**Comment by saranshisatgit** [comment]
Perhaps you could merge this one #5005  ?

**Comment by saranshisatgit** [comment]
Closing this one since it cannot be merged and is creating this signing issue with CLA

**Pull request closed without merging**
