### PR TITLE
fix: Login In UI button 

### PR DESCRIPTION
**Pull request by Kaneki-Ken-7**
Fixes : #3454 

I changed the css of button hover to transparent. I saw figma design there wasn't any hover effect so I made it normal button without any hover effect. 

AFFiNE

### CODE REVIEW

**Review by himself65 — CHANGES_REQUESTED** [review]
No i dont think use important is a good approach

**Comment by Kaneki-Ken-7** [comment]
should I make a new button component for the SignIn button?

**Comment by Kaneki-Ken-7** [comment]
@himself65 I added a new button style for this component. is it ok?

**Comment by Kaneki-Ken-7** [comment]
@QiShaoXuan can you check my PR?

**Comment by QiShaoXuan** [comment]
I am sorry I think this PR could be closed

**Comment by Kaneki-Ken-7** [comment]
> Thank you very much for your pull request, I am sorry our design team has not consider to have a transparent type button, and this issue has fixed in #3477, button has became a plain button.

ok

**Pull request closed without merging**
