### PR TITLE
feat: bootstrap support

### PR DESCRIPTION
**Pull request by darkskygit**
fix needing to repeatedly add upgrade prompt migrations
fix AFF-1075

### CODE REVIEW

**Comment by darkskygit** [comment]
* **#7072** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/7072?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @darkskygit and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by forehalo** [comment]
we will soon have an admin panel where we can manage prompts

**Comment by darkskygit** [comment]
> we will soon have an admin panel where we can manage prompts

i think temporary and emergency prompt fixes can use the admin panel, however, all updates still need to be synchronized to the repository
because the content of the prompt is related to the frontend interaction, old versions of prompt may not support future versions of the front end

**Comment by forehalo** [comment]
> > we will soon have an admin panel where we can manage prompts
> 
> i think temporary and emergency prompt fixes can use the admin panel, however, all updates still need to be synchronized to the repository
> because the content of the prompt is related to the frontend interaction, old versions of prompt may not support future versions of the front end

all prompts are read from db when used, so we will just need to sync the prompts to the latest in case of brand new deployments. Prompts CRUD in admin panel equals data migrations

**Comment by darkskygit** [comment]
> > > we will soon have an admin panel where we can manage prompts
> > 
> > 
> > i think temporary and emergency prompt fixes can use the admin panel, however, all updates still need to be synchronized to the repository
> > because the content of the prompt is related to the frontend interaction, old versions of prompt may not support future versions of the front end
> 
> all prompts are read from db when used, so we will just need to sync the prompts to the latest in case of brand new deployments. Prompts CRUD in admin panel equals data migrations

lgtm

**Pull request closed without merging**
