### PR TITLE
feat: provide i18n for deleted content

### PR DESCRIPTION
**Pull request by zqran**

### CODE REVIEW

**Comment by zqran** [comment]
> @zqran is attempting to deploy a commit to the **toeverything** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=toeverything&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%220ea76407ce7cb165a4b619c997923e5031f25595%22%7D%2C%22id%22%3A%22QmfXJjk9YTfLPUK3iRUte4Bbsb4RkyHXEt4hNZRh8hY72t%22%2C%22org%22%3A%22toeverything%22%2C%22prId%22%3A1289%2C%22repo%22%3A%22AFFiNE%22%7D).

@Himself65 please help

**Review by Himself65 — APPROVED** [review]

**Comment by darkskygit** [comment]
It is recommended to update translate fields through our translation platform: https://i18n.affine.pro
cc @JimmFly may be need to invite contributor?

**Comment by JimmFly** [comment]
> It is recommended to update translate fields through our translation platform: https://i18n.affine.pro cc @JimmFly may be need to invite contributor?
I think @ShortCipher5  can help you guys.

**Comment by zqran** [comment]
@ShortCipher5 Please help me with https://i18n.affine.pro

**Pull request closed without merging**
