### PR TITLE
fix: click continue with ai not work

### PR DESCRIPTION
**Pull request by regischen**

### CODE REVIEW

**Comment by regischen** [comment]
* **#7374** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/7374?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @regischen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by EYHN — APPROVED** [review]

**Review by CatsJuice — APPROVED** [review]

**Review by pengx17 — COMMENTED** [review]
The bug should be caused by temporaryParams here.
We'd better not let affine to directly access chat panels' internal value in run time. A proper solution might be exposed through the ChatPanel's interface.

**Comment by regischen** [comment]
> The bug should be caused by temporaryParams here.
> We'd better not let affine to directly access chat panels' internal value in run time. A proper solution might be exposed through the ChatPanel's interface.
> 
> 

The bug is because the handler is in chat-cards component, but it is not rendered when there are histories.

**Comment by fundon** [comment]
This is a workaround. 

There should be a better solution, can we use localstorage for temporary storage?

**Pull request merged**
