### PR TITLE
feat: tauri desktop client app

### PR DESCRIPTION
**Pull request by linonetwo**
Introducing a new folder `./client-app` containing [https://github.com/tauri-apps/tauri/](https://github.com/tauri-apps/tauri/) based desktop app. Written in rust, to better cooperate with [Octobase](https://github.com/toeverything/OctoBase).

The app stores data to `~/Documents/affine` by default, by using [https://github.com/toeverything/OctoBase](https://github.com/toeverything/OctoBase). Octobase will manipulate sqlite to handle the save&load.

Octobase is currently imported as a git-submodule `client-app/src-OctoBase` (will refactor to rust crate after stabilized). 

## IPC

In `client-app/src-tauri/src/commands` we expose some IPC API from Rust to the JS side, handling CRUD of workspace, blob, yDoc.

A datacenter provider also added to `packages/data-center/src/provider/tauri-ipc` to use those IPC methods.

TS types are generated from rust structs in `client-app/src-tauri/types/src` to `packages/data-center/src/provider/tauri-ipc/ipc/types`, using script in `client-app/src-tauri/examples/generate-jsonschema.rs`. (Run this script using `cd client-app && pnpm build:rs-types`)

## Frontend

After running `pnpm build:affine` in `client-app` folder, build script will build affine with `$.env.BASE_PATH = '/affine-out';` and put the dist HTML to `client-app/public/affine-out`, which will be bundled with tauri.

Then in production, code in `client-app/src-tauri/src/main.rs` will try to load `"affine-out/index.html"`.

And in development, the `"devPath": "http://localhost:8080",` config in `client-app/src-tauri/tauri.conf.json` will try to load dev page served by running `pnpm dev:prerequisite` in `client-app`.

How does Affine's code know it is running inside tauri and should use IPC method instead of indexedDB? By running `pnpm build:preload`, we will build `client-app/src/preload/index.ts` into `client-app/public/preload/index.js`, and loaded by `let preload =` _`include_str!`_`("../../public/preload/index.js");` in `client-app/src-tauri/src/main.rs`, which will inject `window.CLIENT_APP = true;`. And affine will do things depending on this flag.

Note that `client-app/src-tauri/tauri.conf.json` already defined the `beforeDevCommand` and `beforeBuildCommand`, so as a developer, you only need to know `pnpm dev:app` and `pnpm build:app`, `tauri.conf.json` will take care of rest of the commands.

### CODE REVIEW

**Review by lawvs — COMMENTED** [review]
Need to remove useless configurations from the `client-app` directory, for example `LICENSE`, `.gitmodules`, `.editorconfig`, `.gitattributes`, `.nvmrc`

**Comment by linonetwo** [comment]
I'm trying to solve `ReferenceError: window is not defined` in playwright

**Comment by himself65** [comment]
should we move `app` into `apps/web` and `client-app` into `apps/desktop`?

/cc @toeverything/official-contributors

**Comment by darkskygit** [comment]
> should we move `app` into `apps/web` and `client-app` into `apps/desktop`?
> 
> /cc @toeverything/official-contributors

LGTM

**Comment by himself65** [comment]
> > should we move `app` into `apps/web` and `client-app` into `apps/desktop`?
> > /cc @toeverything/official-contributors
> 
> LGTM

If so. I can handle it in the next PR. This PR's job is too much

**Review by darkskygit — APPROVED** [review]

**Comment by linonetwo** [comment]
> should we move `app` into `apps/web` and `client-app` into `apps/desktop`?

@Himself65 Seems we discussed this last month, and we thought letting the client app be on the top level is good for visitors to know its existence @tzhangchi @doodlewind

**Pull request merged**
