### PR TITLE
fix(core): unexpected routing history appears on the shared page

### PR DESCRIPTION
**Pull request by JimmFly**
close AF-1429

https://github.com/user-attachments/assets/a99cf79d-3615-4e0f-835c-2e66b1a34863

### CODE REVIEW

**Comment by JimmFly** [comment]
* **#8356** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8356?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JimmFly and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by fundon** [comment]
https://github.com/toeverything/AFFiNE/blob/503e020412f94df18fd9ba112ed305477217b168/packages/frontend/core/src/components/affine/reference-link/index.tsx#L168-L179

Add `e.stopPropagation();` and  the problem can also be fixed.

**Comment by fundon** [comment]
I switched to this branch and the query string will still be lost.
<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/8ypiIKZXudF5a0tIgIzf/a6b2444e-fc33-4d3f-a545-ced0da0e1a5c.mov">
              
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8ypiIKZXudF5a0tIgIzf/a6b2444e-fc33-4d3f-a545-ced0da0e1a5c.mov">Screen Recording 2024-09-23 at 18.41.24.mov</video>

**Comment by JimmFly** [comment]
That's another question. Maybe we shouldn't use navigate? After all, it is an a tag.

**Comment by fundon** [comment]
> That's another question. Maybe we shouldn't use navigate? After all, it is an a tag.

Try it https://github.com/toeverything/AFFiNE/pull/8356#issuecomment-2367828979

**Comment by JimmFly** [comment]
> > That's another question. Maybe we shouldn't use navigate? After all, it is an a tag.
> 
> Try it [#8356 (comment)](https://github.com/toeverything/AFFiNE/pull/8356#issuecomment-2367828979)

I mean the anchor tag shouldn't have an additional click-to-jump event.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#:~:text=Anchor%20elements%20are,a%20real%20URL.

**Comment by fundon** [comment]
We need to keep the full link address.
You can add a block link for testing.

**Review by EYHN — APPROVED** [review]

**Pull request merged**
