### PR TITLE
Update printer.js

### PR DESCRIPTION
**Pull request by heng1025**

### CODE REVIEW

**Review by doodlewind — CHANGES_REQUESTED** [review]
This may not be the officially maintained package. Could you please justify?

**Comment by heng1025** [comment]
> This may not be the officially maintained package. Could you please justify?

in `app/package.json`,it 's a dev dependency.

**Comment by darkskygit** [comment]
> in `app/package.json`,it 's a dev dependency.

It seems that some previous commits have mixed this problematic package, and we will clean it up later.

**Comment by chucklu** [comment]
https://twitter.com/ewind1994/status/1610868861976604673
Today we found a PR trying to poison our GitHub project 😨. This `chalk-next` parody package is malicious and will try to collect your config and delete your local files 👎. Beware!

**Comment by chucklu** [comment]
chalk-next was introduced in https://github.com/toeverything/AFFiNE/pull/637/files#diff-9fa008865bef344ab2f931a4ddf20163882b86ee764718adacf098dc19991946R48 by @darkskygit 
and removed in https://github.com/toeverything/AFFiNE/commit/14507d0fc0d608611afd076bbb88f252933665b9 by @darkskygit

**Pull request closed without merging**
