### PR TITLE
build: use swc

### PR DESCRIPTION
**Pull request by Flrande**

### CODE REVIEW

**Comment by Flrande** [comment]
need wait for #838 merged

**Comment by darkskygit** [comment]
now you can merge master to use new actions

**Comment by darkskygit** [comment]
it seems that switching to swc will prevent the [babel plugin](https://github.com/istanbuljs/babel-plugin-istanbul) used for coverage

**Comment by Flrande** [comment]
see https://github.com/toeverything/AFFiNE/pull/847

**Review by himself65 — APPROVED** [review]

**Comment by darkskygit** [comment]
i'm try this plugin that can add coverage support with swc: https://github.com/kwonoj/swc-plugin-coverage-instrument

**Comment by himself65** [comment]
> i'm try this plugin that can add coverage support with swc: https://github.com/kwonoj/swc-plugin-coverage-instrument

Please don't waste time on code coverage; It sounds like we have many tests that we have are worth coverage :(

**Pull request merged**
