### PR TITLE
feat(web): drag page to trash folder

### PR DESCRIPTION
**Pull request by SevenOutman**
Drag a page from All Pages list onto the Trash folder in sidebar to move that page into Trash list.

https://github.com/toeverything/AFFiNE/assets/8225666/8d5323f5-cefa-410f-afde-c8897bbf3d3c

### What about confirmation before moving to trash?

Moving to trash is a recoverable action, thus a confirmation is not essential. I would suggest a non-blocking experience for drag-and-drop interaction.

If we must consider mistake proofing, we could add an "Undo" button on the success message alert so that user has instance access to recovering.

---

This PR suppresses #2216, the changes of which are out-dated with the latest sidebar design.

### CODE REVIEW

**Review by pengx17 — DISMISSED** [review]
Well done!

**Review by himself65 — DISMISSED** [review]

**Comment by himself65** [comment]
Could you please resolve the conflicts?

**Comment by SevenOutman** [comment]
> Could you please resolve the conflicts?

I've resolved the conflicts. But the E2E tests are failing on my local machine. The error message indicates that `v-line` won't appear, but it's working fine in the browser. No idea what I missed.

image

**Comment by SevenOutman** [comment]
Hi @Himself65 @pengx17, I've updated the branch with latest `master` again. Would there be some progress on this PR soon?

**Comment by pengx17** [comment]
@SevenOutman It's ready to be merged, but we have to make sure all workflows passed

**Comment by pengx17** [comment]
@SevenOutman looks like E2E tests are still failing. Are you working on them right now?

**Comment by SevenOutman** [comment]
> @SevenOutman looks like E2E tests are still failing.

I checked the e2e case and found that the failure is caused by `dnd-kit` setting `role="button"` on draggable element, resulting in the `.getByRole('cell')` locator failing to find the `<td>` element.

I've updated DraggableTitleCell component to render an extra `<button>` element for dragging interaction inside the `<td>`, in order to preserve the `role="cell"` semantic. Failed e2e cases are passing on my local environment now.

Before

```html
<!-- `.getByRole('cell') can't find this -->
<td role="button">
  Page title
</td>
```

After

```html
<td>
  <button>
    Page title
  </button>
</td>
```

**Review by pengx17 — APPROVED** [review]

**Pull request merged**
