### PR TITLE
fix(electron): set client border style to false by default on windows

### LINKED ISSUE #3714: Set `Client Border Style` to false by default on Windows platform
It's ugly on Windows

### PR DESCRIPTION
**Pull request by Sarvesh521**
fix #3714

### CODE REVIEW

**Review by himself65 — APPROVED** [review]

**Comment by Sarvesh521** [comment]
@himself65 can you guide on how to proceed after this point ?

**Comment by himself65** [comment]
> @himself65 can you guide on how to proceed after this point ?

It's weird because I think the tests should pass

**Comment by himself65** [comment]
> > @himself65 can you guide on how to proceed after this point ?
> 
> It's weird because I think the tests should pass

I found that it's our component bug

**Comment by himself65** [comment]
Thanks for your contribution. The initial code, though, doesn't solve the essential problem(actually the PR is the same as https://github.com/toeverything/AFFiNE/pull/3811) but hope you both can get inspired on how to contribute to AFFiNE.

**Comment by Sarvesh521** [comment]
@himself65 I thought adding that extra if condition to check if it was win32 would have solved the problem. Thanks for helping me. Will try to fix other issues with the experienced gained here.

**Pull request merged**
