### PR TITLE
refactor: environment setup

### PR DESCRIPTION
**Pull request by Simon-He95**

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
Could you please move `isWindow` to a single file?

**Comment by Simon-He95** [comment]
> Could you please move `isWindow` to a single file?

done~

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
```
➜  AFFiNE git:(Simon-He95/master) git push https://github.com/Simon-He95/AFFiNE.git HEAD
Enumerating objects: 422, done.
Counting objects: 100% (367/367), done.
Delta compression using up to 8 threads
Compressing objects: 100% (202/202), done.
Writing objects: 100% (242/242), 21.01 MiB | 8.41 MiB/s, done.
Total 242 (delta 163), reused 47 (delta 31), pack-reused 0
remote: Resolving deltas: 100% (163/163), completed with 88 local objects.
To https://github.com/Simon-He95/AFFiNE.git
 ! [remote rejected]   HEAD -> Simon-He95/master (permission denied)
error: failed to push some refs to 'https://github.com/Simon-He95/AFFiNE.git'
```

**Comment by himself65** [comment]
Closed in https://github.com/toeverything/AFFiNE/pull/2898

**Pull request closed without merging**
