### PR TITLE
fix: remove useRef in menu & tooltip

### LINKED ISSUE #4362: The language switching menu does not pop up correctly
https://github.com/toeverything/AFFiNE/assets/102217452/672350fb-a79f-464a-b404-ecb261e0a950

### LINKED ISSUE #4381: Can't select the language box when the font is in sans
Image

### PR DESCRIPTION
**Pull request by QiShaoXuan**
fixed: https://github.com/toeverything/AFFiNE/issues/4362
fixed: https://github.com/toeverything/AFFiNE/issues/4381
fixed export, collection menu can not trigger

In the past, ref was used because some components did not have specifications, which caused problems with zIndex. Now new components have been migrated, and ref also brings bugs

### CODE REVIEW

**Review by Brooooooklyn — CHANGES_REQUESTED** [review]
Can you add some e2e tests to prevent these cases in the future?

**Comment by QiShaoXuan** [comment]
> Can you add some e2e tests to prevent these cases in the future?

It has really added https://github.com/toeverything/AFFiNE/blob/1aec1ce7d0bc21e8443c1fc2837b540bed80dc41/tests/affine-local/e2e/settings.spec.ts#L23
This bug only appears online, but not in local and test environment

**Comment by QiShaoXuan** [comment]
@himself65 I think UI Review error is since merged the error snapshot last time

**Comment by Brooooooklyn** [comment]
> This bug only appears online, but not in local and test environment

Why?

**Review by himself65 — CHANGES_REQUESTED** [review]
add e2e test

**Comment by himself65** [comment]
> > This bug only appears online, but not in local and test environment
> 
> Why?

I think maybe electron capture some event or something. need to also add test on that side

**Comment by QiShaoXuan** [comment]
> > > This bug only appears online, but not in local and test environment
> > 
> > 
> > Why?
> 
> I think maybe electron capture some event or something. need to also add test on that side

Not electron, it appear on the web page

**Comment by QiShaoXuan** [comment]
> > > > This bug only appears online, but not in local and test environment
> > > 
> > > 
> > > Why?
> > 
> > 
> > I think maybe electron capture some event or something. need to also add test on that side
> 
> Not electron, it appear on the web page

I think the cause of this bug is due to the container that set menu through ref, ref did not update the menu component, but it is strange that this issue only occurs online(web and electron)

**Pull request merged**
