### PR TITLE
fix: use sgtpooki/file-type for resolving image type

### PR DESCRIPTION
**Pull request by pengx17**

### CODE REVIEW

**Comment by pengx17** [comment]
* **#7326** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/7326?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @pengx17 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by forehalo — COMMENTED** [review]
this library is ridiculous, can we really trust it?

**Comment by pengx17** [comment]
> this library is ridiculous, can we really trust it?

There could be other image types like webp that we may also need to introduce soon. Besides blocksuite already has its as the dependency in https://github.com/toeverything/blocksuite/blob/45bdebd333aef568fd4c0e7bd5aebf9e6a8662f0/packages/blocks/src/attachment-block/utils.ts#L185.

**Comment by forehalo** [comment]
@pengx17 I dont know the reason but why don't we use `file-type` directly? browser support is included after I checked

**Review by EYHN — APPROVED** [review]

**Comment by EYHN** [comment]
> @pengx17 I dont know the reason but why don't we use `file-type` directly? browser support is included after I checked

More context:

https://github.com/toeverything/blocksuite/pull/6803
https://github.com/sindresorhus/file-type/issues/578

**Comment by forehalo** [comment]
I prefer easily patching file-type with yarn by our own

**Comment by EYHN** [comment]
> I prefer easily patching file-type with yarn by our own

I also tried patch, but the reference to `node:buffer` comes from his upstream package `token-types`

**Pull request merged**
