### PR TITLE
feat: PWA support

### LINKED ISSUE #257: [feature]: Add PWA function
### 1~3 main use cases of the proposed feature

Make it more like a desktop application.
Send shortcut to desktop, and open it in a browser container.

### Ideas for solution

PWA(Progressive Web App)

### what types of users can benefit from using your proposed feature

more like open the shotcut than type a url to open a product users

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pingren**
Will close #257

https://user-images.githubusercontent.com/5123601/197326132-e4ce040f-0a1c-471d-aabf-3ddf314e20f4.mp4

**NOTES**
If you like to test it with `pnpm start` locally, please git checkout to 1cabbf9cc6a895f3319e5b8533ac77e7df9c88c8.

### CODE REVIEW

**Comment by tzhangchi** [comment]
Thx, Appreciate for your contribution

**Comment by pingren** [comment]
Why is this PR closed?

**Comment by darkskygit** [comment]
Sorry, this was an automatically triggered shutdown because I just archived our old release branch - now the branch name is Pre-Alpha.
It should be reminded that we have been refactoring our editor for the past two months, and it is now stable and ready to be released in the near future. You can try it on https://pathfinder.affine.pro, currently It already includes the most basic rich text editing experience and local-first collaboration functions. From next month, we will begin to transplant the original functions in livedemo to the new version.
If you still want to fix the old version of the editor, I welcome you to reopen the pr, but please note that the target branch of pr is selected as "Pre-Alpha".

**Comment by pingren** [comment]
I can't reopen this PR, therefore I have to create a new one: https://github.com/toeverything/AFFiNE/pull/568

No one reviews this PR **for two months**. If your team welcome external contributions, **please review the PR or at least leave some comments before to close it**. Otherwise, I suggest closing the original issue or do not label it is “helped wanted”.

**Pull request closed without merging**
