### PR TITLE
fix: add missing Korean translations for updated English text

### PR DESCRIPTION
**Pull request by NavyStack**
Korean translation is provided "as is".

---

* Fixed some typos.
* Made adjustments to clarify subtle semantic differences in the original text, which may have identical translations in Korean.
* Unified different translations of the same word to ensure consistency.
* Rearranged the word order to better match Korean sentiment.
* Rearranged the sentence structure to accommodate the Korean subject marker.
* Selected comprehensive terms to distinguish between words that have similar translations in Korean.
* Removed double-passive expressions that are commonly found in Korean translations.
* We have striven to maintain the original sentence structure as closely as possible.
* If the original text lacks a period, the translation into Korean also omits it, rendering the content as a short phrase rather than a full sentence.

---

Fine-tuning the Korean translation is essential. 
However, I would greatly appreciate your guidance on how to access the development server or use Tolgee.

### CODE REVIEW

**Review by ShortCipher5 — APPROVED** [review]
LGTM

**Comment by ShortCipher5** [comment]
Thanks for the contribution here @NavyStack.

We'll look at getting this merged. 

It's worth noting that to make things easier for translations, they are normally done through our dedicated platform - more info here: https://community.affine.pro/c/i18n-general/

**Review by joooye34 — APPROVED** [review]

**Review by joooye34 — APPROVED** [review]

**Comment by NavyStack** [comment]
@ShortCipher5, firstly, I must extend my sincere thanks for your endeavours. However, on a personal note, I have a preference for accurate and natural translations over simpler methods.

The usage of translation platforms can at times lead to delays in updates. Hence, I favour a thorough review and the application of these changes rather than their immediate integration into the mainstream. This is particularly paramount for a platform that shall be closely used and engaged with by users over a prolonged period.

For instance, in English, speakers do not perceive 'have' and 'has' by separating the 'ha-' and the subsequent parts. Rather, each word is understood in its entirety, considering its overall meaning and grammatical function. In contrast, in Korean, each suffix or prefix might carry varied meanings depending on the context.

Grasping the unique challenges posed by the Korean language, wherein context plays a pivotal role in conveying accurate meanings, is essential. As Korean is an agglutinative language, reusing certain sentences can result in awkward or incomplete sentences depending on the context.

Consequently, I wish to establish a test environment locally for detailed fine-tuning. This approach will ensure that the translations not only maintain their linguistic integrity but also resonate more authentically with the intended users.

**Comment by NavyStack** [comment]
Excuse me, when I execute the command `yarn dev`, does it prompt a selection screen? 
Initially, I believed it had paused due to an error, but I have since resolved the issue.
I plan to make some refinements and will be submitting a pull request soon.

**Pull request merged**
