### PR TITLE
fix: added scrollbar at the correct position

### PR DESCRIPTION
**Pull request by Kaneki-Ken-7**
Fixes: #3499 

if you want to change the scrollbar width and color . I can make the changes. @JimmFly

### CODE REVIEW

**Comment by JimmFly** [comment]
https://github.com/toeverything/AFFiNE/assets/102217452/ef0ac335-fdb1-4819-8909-e59253145b11

It would be even better if this could be fixed.

**Review by JimmFly — COMMENTED** [review]
To fix this jittering issue, perhaps you can try the following changes:
```
 '&.scroll': {
      flexGrow: 1,
      overflowY: 'auto', =====> overflowY: 'hidden',
    },
```

**Comment by Kaneki-Ken-7** [comment]
> overflowY: 'hidden'

I have changed the it according to you but I didnt had any jitter issues like you have

**Comment by JimmFly** [comment]
> > overflowY: 'hidden'
> 
> I have changed it according to you but I didnt had any jitter issues like you have

This happens when the viewport is narrow enough.

**Review by JimmFly — APPROVED** [review]

**Pull request merged**
