### PR TITLE
refactor(electron): move electron-api to framework

### PR DESCRIPTION
**Pull request by pengx17**
fix AF-1394

### CODE REVIEW

**Comment by pengx17** [comment]
* **#8630** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#8601** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#8597** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#8588** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8588?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @pengx17 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by forehalo — COMMENTED** [review]
[cool](https://app.graphite.dev//settings/meme-library?org=toeverything)

**Review by forehalo — COMMENTED** [review]
should we standardize the js bridge for UI? adaptation for ios/android is coming.
some of the apis are not applicable for ios/android env. for example, `ui.isMaximized`, `ui.tabXXX`. it makes more sense to move them to `apis.windowManager` or whatever, and make it optional because there won't be such manager in ios/android env

**Comment by pengx17** [comment]
I agree with you, but I didn't foresee the required API/abstraction for mobile. Maybe we can have another js bridge abstraction for mobile, instead of mangling the two together for clearance?
Most desktop APIs are proprietary to Electron and should only be used in components flagged by `isElectron`, meaning the abstraction won't be shared across mobile. Currently, mobile components are being gradually rewritten from scratch. The exception is database-related ones, which are abstracted in data modules.

**Comment by forehalo** [comment]
mobile will have its native sqlite apis

**Review by EYHN — APPROVED** [review]

**Pull request merged**
