### PR TITLE
fix(core): long page title issue in page history

### PR DESCRIPTION
**Pull request by pengx17**

### CODE REVIEW

**Comment by pengx17** [comment]
Current dependencies on/for this PR:
* `canary`
  * **PR #5435** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5435?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #5436** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5436?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5436?utm_source=stack-comment).

**Review by CatsJuice — COMMENTED** [review]
Isn't it necessary to set `white-space: nowrap` here?

**Comment by pengx17** [comment]
Seems unnecessary, but I will add it

**Comment by CatsJuice** [comment]
Since the test case in your screenshots is  regarded as a very long word, `nowrap` is not necessary for this situation. Sentences composed of multiple words should be tested too.

**Review by joooye34 — APPROVED** [review]

**Review by CatsJuice — APPROVED** [review]

**Pull request merged**
