### PR TITLE
Update zh-Hans.json

### PR DESCRIPTION
**Pull request by Nikaple**

### CODE REVIEW

**Review by doodlewind — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by darkskygit** [comment]
cc @JimmFly Do we now have the ability to synchronize language packages back to the translation platform? If not, invite contributors to translate on the translation platform.

**Comment by JimmFly** [comment]
> cc @JimmFly Do we now have the ability to synchronize language packages back to the translation platform? If not, invite contributors to translate on the translation platform.

Yes, that's right, all our keywords have been uploaded to the translation platform, and community contributors are welcome to translate.

**Comment by ShortCipher5** [comment]
I've sent you an invite, along with more details for the i18n project, to the email linked to your GitHub account.

**Comment by Nikaple** [comment]
Thanks for invitation! Since translations are all processed with tolgee, I guess this PR could be closed?

**Comment by darkskygit** [comment]
Yes, I will now turn off the pr, and then you can submit any new translation through our i18n platform. We will mark all users involved in the translation at the release time and on the readme page:) If you have any changes related to the affine code, you are also welcome to pf!

**Pull request closed without merging**
