### PR TITLE
build: fix electron release build process

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Review by himself65 — APPROVED** [review]

**Review by himself65 — DISMISSED** [review]

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/actions/runs/5000536889/jobs/8958120512

**Comment by himself65** [comment]
Error: 'macos' is an invalid platform. Choices are 'darwin', 'mas', 'win32' or 'linux'.

**Comment by pengx17** [comment]
The reason of using macos instead of darwin is that normal user does not know what darwin is when looking for downloads in the download page :D

**Comment by Brooooooklyn** [comment]
> The reason of using macos instead of darwin is that normal user does not know what darwin is when looking for downloads in the download page :D

normal users should come from our home page rather than the GH releases page

**Review by pengx17 — DISMISSED** [review]
Please double check if the new naming rules still work in https://affine.pro/download

**Review by pengx17 — APPROVED** [review]

**Pull request merged**
