### PR TITLE
Feat/e2etest 20230206

### PR DESCRIPTION
**Pull request by tzhangchi**
add  and fix e2e test

- [x] exception page
- [x] preset workspace name
- [x] preset workspace avatar
- [x] preset workspace list 
- [x] create multi workspace

### CODE REVIEW

**Comment by tzhangchi** [comment]
@darkskygit please help me to troubleshooting the ci error, I pass the e2e test locally
image

**Comment by tzhangchi** [comment]
@darkskygit please help me to troubleshooting the error of ci, I pass all e2e test successfully locally
image

**Comment by darkskygit** [comment]
errrors related to test process confirmed that work fine
some tests look unstable cc @JimmFly @tzhangchi

**Review by darkskygit — APPROVED** [review]

**Comment by darkskygit** [comment]
> errrors related to test process confirmed that work fine some tests look unstable cc @JimmFly @tzhangchi see test-result-main: https://github.com/toeverything/AFFiNE/actions/runs/4105342585 look the video, the final result is correct, but the test did not wait until the data changed.

temporarily disable 3 tests, remember to fix them later @JimmFly @tzhangchi

**Pull request merged**
