### PR TITLE
feat: modify prefixUrl in params

### PR DESCRIPTION
**Pull request by himself65**

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
blocking until @darkskygit finished CROS support

**Comment by darkskygit** [comment]
> blocking until @darkskygit finished CROS support

fixed

**Comment by himself65** [comment]
> > blocking until @darkskygit finished CROS support
> 
> fixed

I think no

https://affine-preview-git-himself65-0305-test-api-toeverything.vercel.app/public-workspace/MTjEmB7Chv-qxl_Yx-Syt?prefixUrl=https://app.affine.pro/

**Comment by darkskygit** [comment]
> > > blocking until @darkskygit finished CROS support
> > 
> > 
> > fixed
> 
> I think no
> 
> https://affine-preview-git-himself65-0305-test-api-toeverything.vercel.app/public-workspace/MTjEmB7Chv-qxl_Yx-Syt?prefixUrl=https://app.affine.pro/

add localhost:8080 and affine-next.vercel.app now
match domain based on partial sub domain need some work, if need be, wait at least until after thursday

**Pull request merged**
