### PR TITLE
chore: cherry pick blocksuite fixes

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Review by himself65 — COMMENTED** [review]
@Flrande please check e2e failure

**Review by Flrande — APPROVED** [review]

**Comment by Flrande** [comment]
Let me check it.

**Comment by Flrande** [comment]
I have tested this particular case locally and found no issues with its corresponding functionality. Perhaps it is related to the way the test case is written.

**Review by Anshpel — COMMENTED** [review]
Р

**Pull request merged**
