### PR TITLE
4570/Disabled-form-item-in-the-settings-can-still-be-operated-via-keyboard

### PR DESCRIPTION
**Pull request by aditya-sodhiya**
Fixes: #4570

- Currently, while pressing the tab key the component gets triggered which puts the focus on it, and after pressing the space key it goes to its child node Switch which activates its event and still gets triggered in disable mode. 
- giving tabIndex to an input skips accessibility when `tab` is pressed. Leveraged this for the above fix.

### CODE REVIEW

**Comment by aditya-sodhiya** [comment]
Fixes: #4570

**Comment by aditya-sodhiya** [comment]
@JimmFly please review my PR whenever you get a chance

**Comment by aditya-sodhiya** [comment]
https://github.com/toeverything/AFFiNE/assets/24322155/6c554f83-ad4f-42aa-827c-693c33b8f306

**Comment by joooye34** [comment]
deprecated with  https://github.com/toeverything/AFFiNE/pull/4605

**Pull request closed without merging**
