### PR TITLE
refactor: use yarn

### PR DESCRIPTION
**Pull request by himself65**

### CODE REVIEW

**Comment by himself65** [comment]
@darkskygit need check cloudflare settings

**Review by pengx17 — COMMENTED** [review]
does yarn cross-env work out-of-the box?

**Comment by himself65** [comment]
> yarn cross-env

I dont know

**Review by pengx17 — APPROVED** [review]
LGTM

**Comment by AlessioGr** [comment]
@himself65 just out of curiosity: what was the reason for moving from pnpm to yarn?

**Comment by himself65** [comment]
> @himself65 just out of curiosity: what was the reason for moving from pnpm to yarn?

pnpm is not compatible with electron

**Pull request merged**
