### PR TITLE
feat(cli): build infra and plugins before dev-core

### LINKED ISSUE #3421: cli: support build infra and plugin before `dev-core`

### PR DESCRIPTION
**Pull request by A1zenSousuke**
Fixes : #3421

### CODE REVIEW

**Review by himself65 — CHANGES_REQUESTED** [review]
It is better to be in watch mode and run in a single script.

**Comment by Kaneki-Ken-7** [comment]
> It is better to be in watch mode and run in a single script.

in watch mode? i wrote the dev-core in single script. do you want build infra and plugins in single script and dev-core in another ?

**Comment by himself65** [comment]
> > It is better to be in watch mode and run in a single script.
> 
> in watch mode? i wrote the dev-core in single script. do you want build infra and plugins in single script and dev-core in another ?

What I want is write all code in https://github.com/toeverything/AFFiNE/blob/2980c1afac8b1ea48426460f2254ce56842129bc/packages/cli/src/bin/dev-core.ts

**Comment by Kaneki-Ken-7** [comment]
@himself65 I have updated the file . is this ok?

**Comment by Kaneki-Ken-7** [comment]
> > > It is better to be in watch mode and run in a single script.
> > 
> > 
> > in watch mode? i wrote the dev-core in single script. do you want build infra and plugins in single script and dev-core in another ?
> 
> What I want is write all code in https://github.com/toeverything/AFFiNE/blob/2980c1afac8b1ea48426460f2254ce56842129bc/packages/cli/src/bin/dev-core.ts

I have written the code in this file and its working. is it the correct solution?

**Review by himself65 — CHANGES_REQUESTED** [review]
do not write it in the callback loop.

**Review by himself65 — COMMENTED** [review]
Here is a good example of how-to

https://github.com/DimensionDev/Maskbook/blob/4d179901cf690bf6d257c19f346d0e411c97173a/packages/scripts/src/utils/awaitChildProcess.ts#L1-L15

**Comment by Kaneki-Ken-7** [comment]
> Here is a good example of how-to
> 
> https://github.com/DimensionDev/Maskbook/blob/4d179901cf690bf6d257c19f346d0e411c97173a/packages/scripts/src/utils/awaitChildProcess.ts#L1-L15

ok. I gave it a try using this function to avoid callback loop. @himself65 can you check the changes

**Review by himself65 — APPROVED** [review]

**Pull request merged**
